name: fsm_gpt
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  bloc: ^8.1.2
  dart_openai: ^4.1.4
  flutter_dotenv: ^5.1.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  kartal: ^3.5.0
  responsive_framework: ^1.1.1
  cached_network_image: ^3.3.0
  multi_dropdown: ^2.1.0
  file_saver: ^0.2.9
  file_picker: ^6.1.1
  pdf: ^3.10.7
  flutter_img: ^0.1.5+111

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  envied_generator: ^0.3.0+3
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
