name: fsm_gpt
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  bloc: ^8.1.2
  dart_openai: ^4.1.4
  envied: ^0.3.0+3
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  kartal: ^3.5.0
  responsive_framework: ^1.1.1
  flutter_graph_view:
    path: ../flutter_graph_view
  cached_network_image: ^3.3.0
  multi_dropdown: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  envied_generator: ^0.3.0+3
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
